/*
 * The real Narrator: `codex exec` in a read-only sandbox, answering with a Narration.
 *
 * This lives in scripts/ rather than src/ because it shells out to a binary on the developer's
 * machine. Nothing the browser loads may import it, and putting it under src/ would make that
 * accident one careless import away.
 *
 * An exit code of 0 is not an answer here. `codex exec` returns 0 having written nothing, having
 * written a refusal in prose, and having written JSON of some other shape entirely, and every one of
 * those reaches this process as a child that succeeded. So four conditions gate the return value,
 * checked in order: exit 0, a non-empty output file, JSON that parses, and JSON that is a Narration.
 * Every other path throws a sentence naming what went wrong, because the generation run that calls
 * this is unattended and the thrown message is the whole diagnostic.
 *
 * `spawn` is injectable so those four failure shapes can be driven without a model call, which is
 * what codex-narrator.spec.mjs does.
 */

import type { ChildProcess, SpawnOptions } from 'node:child_process';
import type { Narration } from '../src/artifact/narration';
import type { Narrator } from '../src/generation/narrator';
import type { Plan } from '../src/planner/plan';
import { spawn as nodeSpawn } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import process from 'node:process';
import { parseNarration } from '../src/artifact/narration';

/**
 * The model, pinned in one place. A narration written by a different model reads differently, so a
 * committed pin is what lets a diff in the generated prose trace back to a deliberate edit here
 * instead of to whatever the vendor rolled out that morning.
 *
 * The pin has to name a model the signed-in account can actually reach. A ChatGPT account rejects
 * some ids outright, and codex reports that on stderr and still exits 0 having written nothing, so
 * the only symptom is a missing output file. `runCodex` reads that as a failed narration, which is
 * correct and also quiet: the run stays green and the site silently loses its prose.
 */
export const CODEX_MODEL = 'gpt-5.6-terra';

/**
 * Reasoning effort, overridden rather than inherited. `codexEnv` forwards `CODEX_HOME`, so without
 * this the prose would track whatever a person last set for their own interactive use, and the box
 * and a laptop could narrate differently from the same commit. Medium because ADR 0001 leaves the
 * model no arithmetic, no dates, and no say in what the tasks are: it is writing sentences over a
 * Plan that is already decided.
 */
export const CODEX_REASONING_EFFORT = 'medium';

/** The binary. The child finds it on the `PATH` that `codexEnv` forwards. */
const CODEX_BIN = 'codex';

/**
 * The schema file `--output-schema` reads off disk. Generated by scripts/generate-schema.ts and
 * committed, because codex opens it by path before any of this code would get a chance to write it.
 */
const SCHEMA_FILE = path.resolve(import.meta.dirname, '../schemas/narration.schema.json');

/**
 * The one call shape this module makes on `node:child_process.spawn`. Written in Node's own
 * `SpawnOptions` and `ChildProcess` so that the real `spawn` satisfies it with no cast, and so that
 * a stand-in has a written description of what it has to provide.
 */
export type SpawnLike = (
	command: string,
	args: readonly string[],
	options: SpawnOptions,
) => ChildProcess;

/**
 * Builds the Narrator. The returned function is an ordinary `Narrator`, so the generation run behind
 * it cannot tell this apart from `fakeNarrator`. Pass `spawn` to drive the call without launching
 * codex; production callers take the default.
 */
export function createCodexNarrator(spawn: SpawnLike = nodeSpawn): Narrator {
	return async (plan: Plan): Promise<Narration> => {
		// Each call gets its own output file. Two generation runs at once would otherwise read each
		// other's answers, and a fixed name left behind by a crashed run would be read as this run's.
		const outputFile = path.join(tmpdir(), `rootstock-narration-${randomUUID()}.json`);

		try {
			const args = codexArgs(outputFile, buildPrompt(plan));
			const { code, stderr } = await runCodex(spawn, args);

			// Condition 1 of 4, and the only one a caller would normally think to check.
			if (code !== 0) {
				throw new Error(
					`codex narrator: \`${CODEX_BIN} exec\` exited with ${describeCode(code)} rather than 0, so no narration was produced.${describeStderr(stderr)}`,
				);
			}

			// Condition 2 of 4: codex left something behind. A missing output file and an empty one are
			// the same failure, so they get the same sentence. Which of the two ways codex managed to
			// exit 0 without answering is nothing a reader could act on.
			const raw = readOutput(outputFile);
			if (raw.trim().length === 0) {
				throw new Error(
					`codex narrator: \`${CODEX_BIN} exec\` exited 0 but wrote nothing to ${outputFile}, so there is no narration to read.${describeStderr(stderr)}`,
				);
			}

			// Condition 3 of 4: what codex wrote is JSON. A model handed a strict output schema can still
			// answer with a refusal in plain prose, and that arrives here as a syntax error.
			const parsed = parseJson(raw, outputFile);

			// Condition 4 of 4: that JSON is a Narration. `parseNarration` throws a sentence naming the
			// field and the value that failed, so `toNarration` carries it into the thrown message.
			return toNarration(parsed);
		}
		finally {
			// The answer is already in memory or the call already failed; either way the file is spent.
			// `force` covers the case where codex never created it.
			rmSync(outputFile, { force: true });
		}
	};
}

/**
 * The argument list. `--ephemeral` keeps the run out of codex's session history and
 * `--skip-git-repo-check` lets it run from any directory, both because this is a one-shot call that
 * leaves nothing behind. `-s read-only` is the sandbox: the call asks for prose, so the model has no
 * business writing files. `-c` pins the reasoning effort over the value `CODEX_HOME`'s config file
 * would otherwise supply. The prompt goes last, as the positional argument, because `runCodex` hands
 * the child stdin from the null device and codex would otherwise wait there for one.
 */
function codexArgs(outputFile: string, prompt: string): readonly string[] {
	return [
		'exec',
		'--ephemeral',
		'--skip-git-repo-check',
		'-s',
		'read-only',
		'-m',
		CODEX_MODEL,
		'-c',
		`model_reasoning_effort="${CODEX_REASONING_EFFORT}"`,
		'--output-schema',
		SCHEMA_FILE,
		'-o',
		outputFile,
		prompt,
	];
}

/**
 * The Plan goes in whole and verbatim. ADR 0001 makes the Plan the only thing a Narration may be
 * about, so any trimming here would let this module decide what the model may write about.
 */
function buildPrompt(plan: Plan): string {
	return [
		'You are writing this week\'s narration for a home gardener. The plan below is final: you are selecting and wording, not planning.',
		'',
		'Write a short summary of the week in the yard. Then, for each task worth reading, write one plain sentence, ordered the way a person should read them. Every taskId must be copied from the plan; never invent one, and leave out any task that is not worth a sentence.',
		'',
		'Add an advisory only for something you noticed that no rule in the plan produced. An empty advisories array is a normal answer.',
		'',
		'Answer with JSON matching the supplied schema, and nothing else.',
		'',
		'Plan:',
		JSON.stringify(plan),
	].join('\n');
}

interface CodexRun {
	readonly code: number | null;
	readonly stderr: string;
}

function runCodex(spawn: SpawnLike, args: readonly string[]): Promise<CodexRun> {
	return new Promise<CodexRun>((resolve, reject) => {
		const child = spawn(CODEX_BIN, args, {
			// stdin is the null device. `codex exec` reads the prompt from stdin whenever the positional
			// argument is absent, so an inherited or piped stdin turns a misbuilt argument list into a
			// child that waits forever instead of failing. 'ignore' makes that mistake fail loudly.
			stdio: ['ignore', 'pipe', 'pipe'],
			env: codexEnv(),
		});

		let stderr = '';
		// Drain both pipes even though only stderr is kept. An undrained pipe fills its buffer and
		// blocks the child, and a child blocked on a full stdout never reaches 'close'.
		child.stdout?.on('data', () => {});
		child.stderr?.on('data', (chunk: Buffer | string) => {
			stderr += String(chunk);
		});

		// When the binary is missing or not executable, codex emits 'error' and never 'close'. Without
		// this listener the promise would never settle.
		child.on('error', (cause: Error) => {
			reject(new Error(
				`codex narrator: could not start \`${CODEX_BIN}\`, so no narration was produced (${cause.message}).`,
				{ cause },
			));
		});

		child.on('close', (code: number | null) => {
			resolve({ code, stderr });
		});
	});
}

/**
 * Everything the child is allowed to see. HOME and CODEX_HOME are where codex finds its credentials
 * and its config; PATH is how it finds its own helpers. Everything else in this process's
 * environment is the generation run's business, not the model's.
 */
const CODEX_ENV_KEYS = new Set(['HOME', 'PATH', 'CODEX_HOME']);

function codexEnv(): NodeJS.ProcessEnv {
	// Copy and delete, rather than the three-key object literal this obviously wants to be. Next
	// augments `NodeJS.ProcessEnv` with a required `NODE_ENV` (node_modules/next/types/global.d.ts),
	// so a literal holding only these three keys does not typecheck as one, and the two types overlap
	// too little for an assertion. This route reaches the same env without adding a variable to the
	// child just to satisfy the compiler.
	const env: NodeJS.ProcessEnv = { ...process.env };
	for (const key of Object.keys(env)) {
		if (!CODEX_ENV_KEYS.has(key)) {
			delete env[key];
		}
	}
	return env;
}

function readOutput(outputFile: string): string {
	try {
		return readFileSync(outputFile, 'utf8');
	}
	catch {
		// An unreadable file and an absent one both mean codex did not answer, and the caller's empty
		// check already says that in a sentence naming the file. Reporting the ENOENT here says less.
		return '';
	}
}

function parseJson(raw: string, outputFile: string): unknown {
	try {
		return JSON.parse(raw);
	}
	catch (cause) {
		throw new Error(
			`codex narrator: \`${CODEX_BIN} exec\` exited 0 but what it wrote to ${outputFile} is not JSON (${describeCause(cause)}), so no narration could be read. It begins: ${excerpt(raw)}`,
			{ cause },
		);
	}
}

function toNarration(parsed: unknown): Narration {
	try {
		return parseNarration(parsed);
	}
	catch (cause) {
		throw new Error(
			`codex narrator: \`${CODEX_BIN} exec\` returned JSON that is not a narration. ${describeCause(cause)}`,
			{ cause },
		);
	}
}

function describeCode(code: number | null): string {
	// Node reports a null code when a signal killed the child. Printed raw, that reads as a missing
	// field in the message rather than as the thing that happened.
	return code === null ? 'no exit code (a signal killed it)' : `code ${code}`;
}

function describeStderr(stderr: string): string {
	const trimmed = stderr.trim();
	return trimmed.length === 0 ? '' : ` It wrote this to stderr: ${excerpt(trimmed)}`;
}

function describeCause(cause: unknown): string {
	return cause instanceof Error ? cause.message : String(cause);
}

const EXCERPT_LIMIT = 500;

function excerpt(text: string): string {
	// A model that answers with prose can answer with pages of it, and all of that inside an exception
	// message buries the sentence explaining the failure.
	return text.length <= EXCERPT_LIMIT ? text : `${text.slice(0, EXCERPT_LIMIT)}…`;
}
