import antfu from '@antfu/eslint-config';
import jsxA11y from 'eslint-plugin-jsx-a11y';

export default antfu(
	{
		react: true,
		nextjs: true,
		typescript: true,
		formatters: {
			css: true,
			html: true,
			markdown: true,
			json: true,
			yaml: true,
		},
		stylistic: {
			indent: 'tab',
			semi: true,
			quotes: 'single',
			arrowParens: 'always',
		},
		rules: {
			'camelcase': ['error', { ignoreImports: true, properties: 'never' }],
			'import/no-default-export': 'off',
			'style/multiline-ternary': 'off',
			'ts/no-explicit-any': 'error',
			'pnpm/yaml-enforce-settings': 'off',
			'node/prefer-global/process': 'off',
			'node/prefer-global/buffer': 'off',
			'@next/next/no-html-link-for-pages': 'error',
			'@next/next/no-img-element': 'error',
			'@next/next/no-sync-scripts': 'error',
			'@next/next/no-head-import-in-document': 'error',
			'@next/next/no-document-import-in-page': 'error',
			'@next/next/no-duplicate-head': 'error',
			'@next/next/google-font-display': 'warn',
			'@next/next/google-font-preconnect': 'warn',
			'@next/next/no-page-custom-font': 'warn',
			'@next/next/no-title-in-document-head': 'error',
			'@next/next/no-unwanted-polyfillio': 'warn',
		},
		ignores: [
			'.next',
			'node_modules',
			'dist',
			'build',
			'coverage',
			'public',
			'out',
			'storybook-static',
			'**/components/ui',
			'*.min.*',
		],
	},
	{
		files: ['**/*.md'],
		rules: {
			'style/no-mixed-spaces-and-tabs': 'off',
		},
	},
	{
		plugins: {
			'jsx-a11y': jsxA11y,
		},
		rules: {
			'jsx-a11y/alt-text': 'error',
			'jsx-a11y/anchor-has-content': 'error',
			'jsx-a11y/anchor-is-valid': 'error',
			'jsx-a11y/aria-activedescendant-has-tabindex': 'error',
			'jsx-a11y/aria-props': 'error',
			'jsx-a11y/aria-proptypes': 'error',
			'jsx-a11y/aria-role': 'error',
			'jsx-a11y/aria-unsupported-elements': 'error',
			'jsx-a11y/click-events-have-key-events': 'error',
			'jsx-a11y/heading-has-content': 'error',
			'jsx-a11y/html-has-lang': 'error',
			'jsx-a11y/img-redundant-alt': 'error',
			'jsx-a11y/interactive-supports-focus': 'error',
			'jsx-a11y/label-has-associated-control': 'error',
			'jsx-a11y/media-has-caption': 'error',
			'jsx-a11y/mouse-events-have-key-events': 'error',
			'jsx-a11y/no-access-key': 'error',
			'jsx-a11y/no-autofocus': 'warn',
			'jsx-a11y/no-distracting-elements': 'error',
			'jsx-a11y/no-interactive-element-to-noninteractive-role': 'error',
			'jsx-a11y/no-noninteractive-element-interactions': 'error',
			'jsx-a11y/no-noninteractive-element-to-interactive-role': 'error',
			'jsx-a11y/no-noninteractive-tabindex': 'error',
			'jsx-a11y/no-redundant-roles': 'error',
			'jsx-a11y/no-static-element-interactions': 'error',
			'jsx-a11y/role-has-required-aria-props': 'error',
			'jsx-a11y/role-supports-aria-props': 'error',
			'jsx-a11y/scope': 'error',
			'jsx-a11y/tabindex-no-positive': 'error',
		},
	},
);
